[package]
name = "betterjeb"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
krpc-mars = { path = "../krpc-mars" }
tokio = { version = "1.44.1", features = ["full"] }

[build-dependencies]
glob = "0.3"
krpc-mars-terraformer = { path = "../krpc-mars-terraformer" }
