[package]
name = "betterjeb"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
krpc-client = { git = "https://github.com/kladd/krpc-client", features = [ "tokio" ] }
tokio = { version = "1.44.1", features = ["full"] }
